const passwordMap = {
  "!厲櫟": "0663",
  "!梅玫": "3192",
  "!春綺樓": "2488",
  "!白貂": "2416",
  "!狼蛛": "3564",
  "!沙姆沙馬宮": "3491",
  "!繡骨臺": "3661",
  "!平蘋": "6651",
  "!安萻": "3565",
  "!佐左": "3591",
  "!佑釉": "0809",
  "!甯檸": "9054",
  "!Hugh‧Hugo": "6781",
  "!修修果": "4472",
  "!黛玳": "7391",
  "!尹隱": "3291",
  "!雙爹": "5391",
  "!大二檸": "5346",
  "!嶽昀": "1964",
  "!烏鴉宅": "6164",
  "!尚姠夏廈": "5588",
  "!娜娜": "做愛阿",
  "!嫣懨":"8641",
  "!卉蕙":"6969",
  "!鄰居":"4521"
};

const characterLinks = {
  "!厲櫟": "https://abr.ge/cx58rq",
  "!梅玫": "https://abr.ge/2it4kj",
  "!春綺樓": "https://abr.ge/wl6xfg",
  "!白貂": "https://abr.ge/qlbwbg",
  "!狼蛛": "https://abr.ge/d1enak",
  "!沙姆沙馬宮": "https://abr.ge/jyk6tg",
  "!繡骨臺": "https://abr.ge/wn6jw6",
  "!平蘋": "https://abr.ge/jusko0",
  "!安萻": "https://abr.ge/aln0384",
  "!佐左": "https://abr.ge/a30ami",
  "!佑釉": "https://abr.ge/tnu3jz",
  "!甯檸": "https://abr.ge/qdvzhc",
  "!Hugh‧Hugo": "https://abr.ge/h33lux",
  "!修修果": "https://abr.ge/keljmm",
  "!黛玳": "https://abr.ge/8geuh8",
  "!尹隱": "https://abr.ge/lr1vls",
  "!雙爹": "https://abr.ge/uein3u",
  "!大二檸": "https://abr.ge/wcssf8",
  "!嶽昀": "https://abr.ge/4v183r",
  "!烏鴉宅": "https://abr.ge/346v3i",
  "!尚姠夏廈": "https://abr.ge/8poma1",
  "!嫣懨":"https://abr.ge/ew63bq",
  "!卉蕙":"https://abr.ge/pf886x",
  "!鄰居":"https://abr.ge/89l75q"
};

const passwordAccessRules = {
  "!厲櫟": "all",
  "!梅玫": "all",
  "!春綺樓": "all",
  "!白貂": "all",
  "!狼蛛": "all",
  "!沙姆沙馬宮": "all",
  "!繡骨臺": "all",
  "!平蘋": "hehe",
  "!安萻": "all",
  "!佐左": "all",
  "!佑釉": "all",
  "!甯檸": "all",
  "!Hugh‧Hugo": "all",
  "!修修果": "hehe",
  "!黛玳": "all",
  "!尹隱": "all",
  "!雙爹": "hehe",
  "!大二檸": "all",
  "!嶽昀": "all",
  "!烏鴉宅": "all",
  "!尚姠夏廈": "all",
  "!娜娜": "hehe",
  "!嫣懨": "all",
  "!卉蕙":"all",
  "!鄰居":"all"
};

module.exports = {
  passwordMap,
  characterLinks,
  passwordAccessRules
};
